---
- name: install mysql package
  yum: name={{ item }} state=present
  with_item:
   - mysql-server
   - MySQL-python 
   - libselinux-python
   - libsemanage-python
- name: configure selinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persisten=yes
  when: ansible_selinux.status == "enabled"

- name: create mysql configuration file
  template: src=my.conf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: start mysql service
  service: name=mysqlld state=started enabled=yes

