---
- name: Install libselinux-python
  yum:  name=libselinux-python state=present

- name: Reload ansible_facts
  setup:

- name: copy the epel repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: set up iptables rules
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart ipthables

